---
name: Testing behest
on:
  issue_comment:
    types: [created]

jobs:
  behest:
    runs-on: ubuntu-latest
    
    steps:
      - uses: wenlock/behest@master
        with:
          # optional; comma-separated list of teams who can run commands
          # If this is not set, user must be admin
          teams: "wenlock"
          # token used for interacting with Issues as actions-bot
          token: ${{ secrets.GITHUB_TOKEN }}
          # token used for elevated operations against Org
          admin_token: ${{ secrets.ADMIN_TOKEN }}
